notes/admin/urls.py
from django.conf.urls.defaults import *
from notebook.notes.models import Note, Tag

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import notes

urlpatterns = patterns('',#'notebook.notes.views',
    # Example:
    #(r'^notebook/', include('notebook.foo.urls')),
    #(r'^$', 'index'),
    #(r'^$', 'django.views.generic.list_detail.object_list', info_dict),
     (r'', include(notes.site.urls)),
 
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^admin/', include(admin.site.urls)),
)

notes/urls.py
from django.conf.urls.defaults import *
from django.contrib import databrowse
from django.views.generic import list_detail

from notebook.notes.models import Note, Tag



# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


#databrowse.site.register(Note)
#databrowse.site.register(Tag)

urlpatterns = patterns('',
   
    (r'^notes/$','notebook.notes.views.index'),

    #TODO: if social app can use this to get tags too
    (r'getWsTags/','notebook.notes.views.get_ws_tags'),
    
    #(r'^notes/tags/$','notebook.notes.views.alltags'), #not used

    (r'^settings/folders/$', 'notebook.notes.views.settings_folders'),
    (r'^settings/folders/folder/(?P<folder_name>[^/]+)/$', 'notebook.notes.views.settings_folder'),
    (r'^settings/folders/folder/(?P<folder_name>[^/]+)/updateFolder/$', 'notebook.notes.views.settings_folder_update'),
    (r'^settings/folders/addFolder/$', 'notebook.notes.views.settings_folder_add'),

    #this below can also match url settings/tags/addTag/. But since it is put after setting's url patterns, it should be fine. TODO:better
    (r'^(?P<aspect_name>[^/]+)/tags/(?P<tag_name>[^/]+)/$','notebook.notes.views.tags'), #TODO:regex here

    (r'/updateNoteInline/$','notebook.notes.views.update_note_inline'), #TODO:maybe no / after updateNote   
    (r'/updateNoteTagsInline/$','notebook.notes.views.update_note_tags_inline'), 
    (r'/addNotesToFrame/$','notebook.notes.views.add_notes_to_frame'), 
    (r'/createNoteInFrame/$','notebook.notes.views.create_note_in_frame'), 


    (r'/addComment/$','notebook.notes.views.add_comment'),
    (r'/deleteComment/$','notebook.notes.views.delete_comment'),
    (r'/makePrivate/$','notebook.notes.views.make_private'),
    (r'/makePublic/$','notebook.notes.views.make_public'),


    (r'/voteUpNote/$','notebook.notes.views.vote_up_note'), 
    (r'/voteDownNote/$','notebook.notes.views.vote_down_note'),
    (r'/deleteNote/$','notebook.notes.views.delete_note'),
    (r'/discardNote/$','notebook.notes.views.discard_note'),
    (r'/restoreNote/$','notebook.notes.views.restore_note'),
    (r'/addNote/$','notebook.notes.views.add_note'),    
    (r'/linkNotes/$','notebook.notes.views.frame_notes'),  
    #(r'^frames/$','notebook.notes.views.frames'),
    (r'^frames/frame/(?P<frame_id>[^/]+)/$','notebook.notes.views.frame'),  
    (r'^linkagenotes/$','notebook.notes.views.linkagenotes'),
    (r'^linkagenotes/note/(?P<note_id>[^/]+)/$','notebook.notes.views.linkagenote'),
    #(r'/updateLinkageNoteInline/$','notebook.notes.views.update_frame_inline'),
    #(r'/deleteLinkage/$','notebook.notes.views.delete_frame'),
    (r'/deleteNoteFromFrame/$','notebook.notes.views.delete_note_from_frame'),    
    (r'/addTags2Notes/$','notebook.notes.views.add_tags_to_notes'),
    #(r'/removeTagsFromNotes/$','notebook.notes.views.remove_tags_from_notes'),

    (r'/addTags2Notes2/$','notebook.notes.views.add_tags_to_notes2'),
    (r'/removeTagsFromNotes2/$','notebook.notes.views.remove_tags_from_notes2'),

    (r'/saveSearch/$','notebook.notes.views.save_search'),

    (r'^folders/(?P<folder_name>[^/]*)/$','notebook.notes.views.folders'),
    (r'^folders/$','notebook.notes.views.folders_index'),

    (r'^caches/(?P<cache_id>[^/]+)/addNotes2Cache/$','notebook.notes.views.add_notes_to_cache'), 
    (r'^caches/(?P<cache_id>[^/]+)/clearCache/$','notebook.notes.views.clear_cache'), 
    #TODO:Might need to update the url for caches. It seems better to be r'^caches/cache/(?P<cache_id>[^/]+)/notes/$'
    (r'^caches/(?P<cache_id>[^/]+)/$','notebook.notes.views.caches'), 
    #below is only for after notebook/  . 
    (r'^frames/frame/(?P<frame_id>[^/]+)/notes/$','notebook.notes.views.included_notes_in_frame'), 
    (r'^linkages/linkage/(?P<linkage_id>[^/]+)/notes/$','notebook.notes.views.included_notes_in_linkage'), 

    (r'^notes/note/(?P<note_id>[^/]+)/$','notebook.notes.views.note'),
    (r'^notes/note_raw/(?P<note_id>[^/]+)/$','notebook.notes.views.note_raw'),
    
(r'^notes/note/(?P<note_id>[^/]+)/updateNote/$','notebook.notes.views.update_note'),
    (r'^notes/note/(?P<note_id>[^/]+)/updateNoteTrans/$','notebook.notes.views.update_note_trans'),
    (r'^linkagenotes/note/(?P<note_id>[^/]+)/updateLinkageNote/$','notebook.notes.views.update_linkagenote'),
    #below actually applied to framebook
    (r'^notes/note/(?P<note_id>[^/]+)/getRelatedFrames/$','notebook.notes.views.get_related_frames'),

    (r'^setNotesPrivate/$','notebook.notes.views.set_notes_private'),
    (r'^setNotesPublic/$','notebook.notes.views.set_notes_public'),

    (r'^notes/note/(?P<note_id>[^/]+)/setOrder/$','notebook.notes.views.set_notes_order_in_frame'),



 




)

urls.py
from django.conf.urls.defaults import *
from notebook.notes.models import Note, Tag

from django.contrib import databrowse

from django.views.generic import list_detail

from env_settings import MEDIA_ROOT, DB_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import settings
import os
import imp
#import postman

#databrowse.site.register(Note)
#databrowse.site.register(Tag)

#import django_cron
#django_cron.autodiscover()

urlpatterns = patterns('',
    # Example:
    #(r'^notebook/', include('notebook.foo.urls')),
     
    (r'^messages/', include('postman.urls')),

    (r'^notification/', include('notification.urls')),

    (r'^getNotices/', 'notebook.notes.views.get_notices'),
   

    (r'^$','notebook.notes.views.root'),
    (r'^myadmin/doc/', include('django.contrib.admindocs.urls')),
    (r'^myadmin/', include('notebook.notes.admin.urls')),

    #TODO: maybe all urls for adding and updating shouldn't have a username in the url, and 
    #should get it from the request 
    (r'^user/bookmarkbook/bookmarks/addBookmark/', 'notebook.bookmarks.views.add_bookmark'), #for the add bookmark browser button 
    (r'^user/scrapbook/scraps/addScrap/', 'notebook.scraps.views.add_scrap'),  #for the add scrap browser button    

    #(r'^users/(?P<username>[^/]+)/$', 'notebook.social.views.wall'),
    (r'^social/(?P<username>[^/]+)/$', 'notebook.social.views.profile'),
    (r'^social/(?P<username>[^/]+)/addFriend/$', 'notebook.social.views.add_friend'),
    (r'^social/(?P<username>[^/]+)/removeFriend/$', 'notebook.social.views.remove_friend'),

#below seem not used
    #(r'^users/(?P<username>[^/]+)/wall/snippets/$', 'notebook.social.views.wall_snippets'),
    #(r'^users/(?P<username>[^/]+)/wall/bookmarks/$', 'notebook.social.views.wall_bookmarks'),
    #(r'^users/(?P<username>[^/]+)/wall/scraps/$', 'notebook.social.views.wall_scraps'),
    (r'^groups/(?P<groupid>[^/]+)/$', 'notebook.social.views.group_index'),
    (r'^groups/(?P<groupid>[^/]+)/tagframes/$', 'notebook.social.views.group_tagframes'),
    (r'^groups/(?P<groupid>[^/]+)/salons/$', 'notebook.salons.views.group_salons'),
    (r'^groups/(?P<groupid>[^/]+)/salons/salon/(?P<salon_id>[^/]+)/$', 'notebook.salons.views.group_salon'),
    (r'^groups/(?P<groupid>[^/]+)/salons/salon/(?P<salon_id>[^/]+)/signup/$', 'notebook.salons.views.group_salon_signup'),

    (r'^groups/(?P<groupid>[^/]+)/joinGroup/$', 'notebook.social.views.join_group'),
    (r'^groups/(?P<groupid>[^/]+)/admin/$', 'notebook.social.views.group_admin'),
    (r'^groups/(?P<groupid>[^/]+)/admin/deleteMember/$', 'notebook.social.views.group_delete_member'),
    (r'^groups/(?P<groupid>[^/]+)/admin/addTags2Group/$', 'notebook.social.views.group_add_tags'),
    (r'^groups/(?P<groupid>[^/]+)/admin/removeTagFromGroup/$', 'notebook.social.views.group_remove_tag'),
    (r'^groups/(?P<groupid>[^/]+)/admin/updateGroup/$', 'notebook.social.views.update_group'),
    (r'^groups/(?P<groupid>[^/]+)/admin/addUsers2Group/$', 'notebook.social.views.group_add_users'),
    (r'^groups/(?P<groupid>[^/]+)/admin/inviteUsers2Group/$', 'notebook.social.views.group_invite_users'),

    (r'^groups/$', 'notebook.social.views.groups'),

    (r'^learners/$', 'notebook.social.views.learners'),
 
    (r'^people/$', 'notebook.social.views.people'),

    (r'^salons/$', 'notebook.salons.views.salons'),
    (r'^(?P<username>[^/]+)/salons/$', 'notebook.salons.views.my_salons'),


    #(r'^groups/(?P<groupid>[^/]+)/snippets/$', 'notebook.social.views.group_snippets'),
    (r'^groups/(?P<groupid>[^/]+)/(?P<bookname>[^/]+)/notes/$', 'notebook.social.views.group'),
    #(r'^groups/(?P<groupid>[^/]+)/(?P<bookname>[^/]+)/notes/note/(?P<note_id>[^/]+)/$', 'notebook.social.views.note'),
    (r'^groups/(?P<groupid>[^/]+)/(?P<bookname>[^/]+)/tags/(?P<tag_name>[^/]+)/$','notebook.social.views.group_tag'),



    #TODO: distinguish btw social notes and notes when merging snippets/bookmarks/scraps back here
    #TODO: better regex
    (r'^groups/[^/]+/[^/]+/addComment/$', 'notebook.social.views.add_comment'),
    (r'^social/.+/addComment/$', 'notebook.social.views.add_comment'),
    (r'^social/.+/addCourse/$', 'notebook.social.views.add_course'),
    (r'^social/.+/deleteOuterlink/$', 'notebook.social.views.delete_outer_link'),
    (r'^social/.+/deleteCourse/$', 'notebook.social.views.delete_course'),

     (r'/friends/.+/notes/addComment/$', 'notebook.social.views.add_comment'),
    (r'^social/(?P<username>[^/]+)/commentsfor/$', 'notebook.social.views.comments_4_user'),
    (r'^social/(?P<username>[^/]+)/commentsby/$', 'notebook.social.views.comments_by_user'),
    #for now, no deleting of social comments TODO:
    (r'^groups/[^/]+/[^/]+/deleteComment/$','notebook.social.views.delete_comment'),
    (r'^social/.+/deleteComment/$','notebook.social.views.delete_comment'),
    #for now, still keep share in notes.views instead of moving to social.views (If moving, might need to move sites binding together) TODO: 
    (r'^social/(?P<bookname>[^/]+)/share/$','notebook.notes.views.share'),


    (r'^social/(?P<username>[^/]+)/mentioned/$', 'notebook.social.views.mentioned'),
    (r'^social/(?P<username>[^/]+)/mentioned_in_note/$', 'notebook.social.views.mentioned_in_note'),
    (r'^social/(?P<username>[^/]+)/mentioned_in_comment/$', 'notebook.social.views.mentioned_in_comment'),

    (r'/voteUseful/$','notebook.social.views.vote_useful'), 
    (r'/voteUnuseful/$','notebook.social.views.vote_unuseful'), 
    (r'/take/$','notebook.social.views.take'), 

    (r'^(?P<username>[^/]+)/addNoteOnly/$', 'notebook.notes.views.add_note_only'),

    (r'^(?P<username>[^/]+)/groups/$', 'notebook.social.views.my_groups'),
    (r'^(?P<username>[^/]+)/groups/addGroup$', 'notebook.social.views.my_groups'),
    (r'^(?P<username>[^/]+)/friends/$', 'notebook.social.views.friends'),
    (r'^suggest/$', 'notebook.social.views.suggest'),
    (r'^(?P<username>[^/]+)/friends/(?P<bookname>[^/]+)/notes/$', 'notebook.social.views.friends_notes2'), 
    (r'^(?P<username>[^/]+)/groups/(?P<bookname>[^/]+)/notes/$', 'notebook.social.views.groups_notes'),
    (r'^(?P<username>[^/]+)/groups/(?P<bookname>[^/]+)/$', 'notebook.social.views.groups_notes'),

    (r'^social/(?P<username>[^/]+)/(?P<bookname>[^/]+)/$', 'notebook.social.views.notes'),
    (r'^social/(?P<username>[^/]+)/(?P<bookname>[^/]+)/notes/$', 'notebook.social.views.notes'),
    (r'^social/(?P<username>[^/]+)/(?P<bookname>[^/]+)/notes/note/(?P<note_id>[^/]+)/$','notebook.social.views.note'),
    (r'^social/(?P<username>[^/]+)/(?P<bookname>[^/]+)/tags/(?P<tag_name>[^/]+)/$', 'notebook.social.views.notes_tag'),
    #might delete this one or the above one
    (r'^social/(?P<username>[^/]+)/(?P<bookname>[^/]+)/notes/tags/(?P<tag_name>[^/]+)/$', 'notebook.social.views.notes_tag'),
    (r'^social/(?P<username>[^/]+)/(?P<bookname>[^/]+)/folders/(?P<foldername>[^/]+)/$', 'notebook.social.views.folders'),

    (r'^social/(?P<username>[^/]+)/(?P<bookname>[^/]+)/notes/note/(?P<note_id>[^/]+)/getRelatedFrames/$','notebook.social.views.get_related_frames'),
 

    (r'^all/(?P<bookname>[^/]+)/notes/$', 'notebook.social.views.all_notes'), 

   #TODO:put tagframes at front, since it doesn't distinguis btw personal and public book. For example /tagframes/username/...
    (r'^(?P<username>[^/]+)/tagframes/$', 'notebook.tags.views.index'),
   # (r'^(?P<username>[^/]+)/tagframes/addTagFrame/$', 'notebook.tags.views.add_tag_frame'),
    (r'^(?P<username>[^/]+)/tagframes/addTags2Frame/$', 'notebook.tags.views.add_tags_2_frame'),
    (r'^(?P<username>[^/]+)/tagframes/removeFrame/$', 'notebook.tags.views.remove_frame'),
    (r'^(?P<username>[^/]+)/tagframes/deleteFrame/$', 'notebook.tags.views.delete_frame'),
    
    (r'^(?P<username>[^/]+)/tagframes/(?P<tag_path>[^/]+)/(?P<bookname>[^/]+)/notes/$', 'notebook.tags.views.notes_by_tag'),
    (r'^social/(?P<username>[^/]+)/tagframes/(?P<tag_path>[^/]+)/(?P<bookname>[^/]+)/notes/$', 'notebook.tags.views.social_notes_by_tag'),
    (r'^(?P<username>[^/]+)/tagframes/getRelatedTags/$','notebook.tags.views.get_related_tags'),  
    (r'^(?P<username>[^/]+)/tagframes/export/$','notebook.tags.views.export'),  


    #below dupldate a lot with patterns in 'notebook.notes.urls', refactor TODO:
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/updateNoteInline/$','notebook.notes.views.update_note_inline'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/updateNoteTagsInline/$','notebook.notes.views.update_note_tags_inline'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/addComment/$','notebook.notes.views.add_comment'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/deleteComment/$','notebook.notes.views.delete_comment'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/makePrivate/$','notebook.notes.views.make_private'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/makePublic/$','notebook.notes.views.make_public'),
    
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/voteUpNote/$','notebook.notes.views.vote_up_note'), 
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/voteDownNote/$','notebook.notes.views.vote_down_note'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/deleteNote/$','notebook.notes.views.delete_note'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/addNote/$','notebook.notes.views.add_note'),  
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/addTags2Notes2/$','notebook.notes.views.add_tags_to_notes2'),
    (r'^(?P<username>[^/]+)/tagframes/(.*)/(?P<bookname>[^/]+)/notes/removeTagsFromNotes2/$','notebook.notes.views.remove_tags_from_notes2'),

    (r'^(?P<username>[^/]+)/tagframes/tagframe/(?P<tagframe_name>[^/]+)/$','notebook.tags.views.tagframe'),

scraps/models.py
from django.db import models

from notebook.notes.models import Note, Tag, WorkingSet, Folder, Cache



class Scrap(Note):
    url = models.CharField(max_length=2000)#models.URLField(max_length=300)


    def __unicode__(self):
        return self.desc

    def get_note_type(self):
        return 'Scrap'
    
    

#class Scrap_Backup(models.Model):
#    url = models.CharField(max_length=300)#models.URLField(max_length=300)  
#    desc =  models.TextField(max_length=200)  #TODO: doesn't seem to be limiting the size
#    title = models.CharField(blank=True,max_length=100)    
#    extra = models.TextField(blank=True,max_length=300)    
#    tags = models.ManyToManyField(Tag,blank=True)  
#    private = models.BooleanField(default=False)
#    init_date = models.DateTimeField('date created', auto_now_add=True)
#    last_modi_date = models.DateTimeField('date last modified', auto_now=True)
#    deleted = models.BooleanField(default=False)
#    vote =  models.IntegerField(default=0) 


  

   
            
#TODO: change back to just Folder, it will be a different db table because of different app
class Scrap_Folder(Folder):
    pass


class Scrap_Cache(Cache):
    cache_id = models.AutoField(primary_key=True)
    


#===============================================================================
# class Bag_Of_Scrap(Bag_Of_Note):    
#    notes = models.ManyToManyField(Scrap) 
#===============================================================================
    

    
class Linkage_Of_Scrap(models.Model):
    title = models.CharField(blank=True, max_length=2000) #TODO: need title?
    desc =  models.TextField(blank=True, max_length=2000)
    tags = models.ManyToManyField(Tag, blank=True)
    private = models.BooleanField(default=False)
    init_date = models.DateTimeField('date created', auto_now_add=True)
    last_modi_date = models.DateTimeField('date last modified', auto_now=True)
    deleted = models.BooleanField(default=False)
    vote =  models.IntegerField(default=0, blank=True)
    notes = models.ManyToManyField(Scrap) #TODO: so far doesn't allow linkage of linkange note

    
    class Meta:
#        unique_together = (("linkage_id","user"),)
        verbose_name = "linkage"    

templates/snippetbook/notes/add_note.html
{% load i18n %}



<div  {% if request.mobile %}class="mobile" {% endif%}>
    <table class="align_table">
        <tr>
            <td>
                <div id="add_note_section">
                    <div class="section_header">
                        <span class="big_font">
                            <img src="/site_media/img/light-bulb.png"/>
                           {{user.username}}, <a href="http://blog.opensourcelearning.org/?p=109" target="_blank">{% trans "What have your learned today?" %}
                                <img src="/media/img/admin/icon-unknown.gif"/></a>:&nbsp;&nbsp;&nbsp;&nbsp;
                        </span>     
                         {% if pagename == 'notes'%}
                        <span class="show_add_note_section"><img title="{% trans 'Show adding snippet' %}" src="/site_media/img/right-arrow.jpg" class="clickable"/></span>
                        <span class="hide_add_note_section"  ><img title="{% trans 'Hide adding snippet' %}" src="/site_media/img/down-arrow.jpg" class="click_img"/></span> 
                        {% endif%}
                     </div>   
            </td>
            <td class="right_td">
                    <span id="charCountSpan">
                            
                            <span id="charCount">0</span> {% trans "letters used" %}
                            </span>
                            <span>{% trans "(< 300 letters)" %}
                                    <img src="/media/img/admin/icon-unknown.gif" title="{% trans "A short snippet is enough to represent a significant experience. Practice on that. :-)" %}"/>
                            </span>&nbsp;
                            <span id="charCount_alert"></span>
   
            </td>
        </tr>
    </table>



<div class="addnote">
        <!--TODO:get ok? it still send an extra request to the server-->
        {% if current_tag %}
            <input type="hidden" name="tags" value="{{current_tag}}"/>
        {% endif %}    
        <table class="align_table">
                <tr><td colspan="2">
                    <textarea id="id_desc" rows="3" cols="85" name="desc" autofocus="autofocus"></textarea>   
                </td></tr>
                <tr><td>    
                    <div>
                            {% trans "Private" %} <input type="checkbox" name="private" id="id_private"/>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span id="add_note_vote_bar">
                                <span class="thumbup"  id="add_note_vote_up"  title="{% trans 'Rank Up Importance' %}"><img src="/site_media/img/thumbUp.gif"/></span>
                                <span class="thumbdown" id="add_note_vote_down"  title="{% trans "Rank Down Importance"  %}"><img src="/site_media/img/thumbDown.gif"/></span>
                                <input type="hidden" name="vote" id="id_vote" value="0"/><span id="add_note_vote">0</span>
                            </span>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span>
                                <span class="tags_img clickable" onclick="javascript:showAddNoteTags();" title="{% trans 'Add tags' %}"><img src="/site_media/img/tags-small.png" class="img_in_notes_section_header"/>
                                </span>
                                <div id="add_note_tags_box">                       
                                    <ul id="add_note_tags"></ul>
                                </div>
                            </span>
                    </td>
                    <td class="right_td">
                        <span id="add_note_submit_button">
                         {% if pagename == 'notes'%}
                            <button class="big clickable" id="add_note_submit"  onclick="javascript:addNote();"/>{% trans 'Add' %}(Alt-S)</button>  
                        {% else %}  
                            <button class="big clickable" id="add_note_submit"  onclick="javascript:addNote();"/>{% trans 'Add' %}</button> 
                         {% endif %}
                        </span>
                    </td>         
                </tr>
        </table>
        
    </div> 
    
 </div>   

templates/snippetbook/notes/add_note_only.html
{% extends "include/base_mini.html" %}
{% load i18n %}

{% block title %}
{% trans "Add snippet" %} 
{% endblock %}

{% block extra_script %}
 <script src="/site_media/js/jquery.hotkeys.js" type="text/javascript" charset="utf-8"></script>	
 
{% include "include/notes/add_note_js.html" %}
{% include "include/notes/update_tags_inline_js.html" %}    

{% endblock %}






{% block content%}
 {% include "snippetbook/notes/add_note.html" %}
 
 {% comment %}Not used currently. If it is wanted to dispaly note added in add note only page, then this can be included.
 {% include "snippetbook/notes/show_added_notes.html" %}
 {% endcomment %}
 {% endblock %}

templates/snippetbook/notes/folders_ special_side_menu.html
{% load i18n %}

<div class="module"> 
        <h2>{% trans "Snippetbook" %}<a href="javascript:alert('{% trans "A snippetbook is dynamic set of snippets that are selected based on certain queries." %}');">
<img src="/media/img/admin/icon-unknown.gif"/></a>  <span class="setting-in-r-menu"><a href="/{{profile_username}}/{{bookname}}/settings/folders/">{% trans "Settings" %}</a></span></h2>       
	{% for folder in folders %}	
		<a href="/{{ profile_username }}/{{bookname}}/folders/{{folder.name}}/" title="{{folder.value}}">{{folder.name}}</a><br/> 
        {% endfor %} 
</div> 

templates/snippetbook/notes/linkages.html
{% extends "notebook/note_list_base.html" %}
{% load i18n %}


{% block tags_menu %}
{% include "include/notes/menu/tags_menu.html" %} 
{% endblock %}

{% block special_side_menu %}
<div class="module"> 
        <h2>{% trans "Linkages" %}</h2>       
        <a href="/{{ profile_username }}/{{bookname}}/linkagenotes/">{% trans "All Linkages" %}</a><br/>
        <a href="javascript:alert('Not implemented yet!');" class="NotImplementedYet">{% trans "Same Topic" %}</a><br/>      
        <a href="javascript:alert('Not implemented yet!');" class="NotImplementedYet">{% trans "Same Event" %}</a><br/> 
</div> 
{% endblock %}

{% block content%}
<div id="content-main">
<div> 
{% include "snippetbook/notes/linkagenotesdisplay.html" %}
</div> 
</div> 
{% endblock %}

templates/snippetbook/notes/note_list.html
{% extends "snippetbook/note_list_base.html" %}
{% load i18n %}




{% block content%}

<div id="content-main"> 
<div> 
{% include "snippetbook/notes/notesdisplay.html" %}
</div> 
</div> 
{% endblock %}

templates/snippetbook/notes/notes.html
{% extends "snippetbook/note_list_base.html" %}
{% load i18n %}



{% block linkage_filter %}
       <h4>{% trans "In linkages" %}</h4>
        {% if in_linkage == 'All' %}
             <span style="font-size:15px">{% trans "All" %}</span><br/>
        {% else %}
            <a href="?in_linkage=All">{% trans "All" %}</a><br/>      
        {% endif %}       
        {% if in_linkage == 'True' %}
             <span style="font-size:15px">{% trans "Yes" %}</span><br/>
        {% else %}
            <a href="?in_linkage=True">{% trans "Yes" %}</a><br/>      
        {% endif %}           
       
{% endblock %}






{% block content%}
<div id="content-main"> 
<div> 
{% include "snippetbook/notes/notesdisplay.html" %}
</div> 
</div> 
{% endblock %}

templates/snippetbook/notes/notes_display.html
{% extends "include/notes/notes_display.html" %}
{% load i18n %}




		   
      

             
           

templates/snippetbook/notes/notesdisplay.html
{% extends "include/notes/notesdisplay.html" %}
{% load i18n %}

{% block extra_ready_script %}
    <script type="text/javascript">

    </script>
{% endblock %}

{% block add_note_section %}<br/>

    
       {% include "snippetbook/notes/add_note.html" %}
    
      


{% endblock %}




{% block notes_section %}
    {% include "snippetbook/notes/notes_display.html" %}
{% endblock %}

templates/snippetbook/notes/show_added_notes.html
{% comment %}Not used currently. If it is wanted to dispaly note added in add note only page, then this can be included.
{% endcomment %}

<div class="notes_display" view_mode="{{view_mode}}">
<ul class="notes_display">


</ul>
</div>